PAGOPA-726 adding stations creditor institutions filter
pagopa/pagopa-api-config-selfcare-integration pull request #2
Opened 2023-03-29 14:14 UTC by FedericoRuzzier

#### List of Changes
Adding a filter for the stations based on the creditor institution

#### Motivation and Context
This change was required by selfcare to properly filter the stations

#### How Has This Been Tested?
This has been tested manually through postman and through Junit tests

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-04-03 14:01 UTC, FedericoRuzzier commented on src/main/java/it/gov/pagopa/apiconfig/selfcareintegration/config/ResponseValidator.java
> +  @AfterReturning(pointcut = "execution(* it.gov.pagopa.apiconfig.controller.*.*(..))", returning = "result")
I think it was right before, reverting

2023-04-04 15:11 UTC, jacopocarlini approved these changes
👍

2023-04-05 07:59 UTC, jacopocarlini requested changes

2023-04-05 07:59 UTC, jacopocarlini commented on openapi/generate_openapi.sh
> +api-spec-converter  --from=openapi_3 --to=swagger_2 ./openapi/openapi.json > ./openapi/swagger.json
in this case we don't need swagger v2 file.
```suggestion
```

2023-04-06 09:55 UTC, jacopocarlini approved these changes
perfect ⭐

2023-04-06 09:55 UTC, jacopocarlini commented
update_code

2023-04-06 13:41 UTC, merged